{    "Logs": "Added object temp to s3 bucket lambda-cpp-me-south-1
    	clock precision level: 3
    	Cache line size: 64 B
    	Found an address that falls on two cache lines: 0x55555644e13c
    	Baseline sample: Size- 1500, Mean- 6803
    	[Lambda-  2] Phase, Position, Bit, Sent, Read, Lat Size, Lat Mean, Lat Std, Lat Max, Lat Min, Base Mean, Base Lat, PValue
    	[Lambda-  2]   0         7    0     0     0      1500      6873     5441    48680     4966       6803     5191 1.000158875671571
    	[Lambda-  2]   0         6    0     0     0      1500      6638     4840    54836     4984       6803     5191 1.000994481483806
    	[Lambda-  2]   0         5    0     0     0      1449      7084     6071    81480     4980       6803     5191 1.001809220754458
    	[Lambda-  2]   0         4    0     0     0      1485     33664  1045131 40280976     4960       6803     5191 1.002120034665219
    	[Lambda-  2]   0         3    0     0     0      1500      7107     6660   136336     4982       6803     5191 1.002518733260693
    	[Lambda-  2]   0         2    0     0     0      1500      6943     5700    41636     4950       6803     5191 1.000608864734707
    	[Lambda-  2]   0         1    1     1     1      1500         0        0        0        0       6803     5191 1.000608864734707
    	[Lambda-  2]   0         0    0     0     0      1477     34421  1043073 40093654     4968       6803     5191 1.002105508096610
    	[Lambda-2] Phase 0, Id read: 2",    "Boot ID": "c282f034-ead7-4f50-b6ed-d0d50335c095",    "MAC Address": "D2:4A:2E:58:9E:E0",    "Phase 1": "2",    "Phases": "1",    "Start Time": "2020-08-14 00:25:55",    "End Time": "2020-08-14 00:26:24",    "Id": "2",    "Request ID": "6a392c40-47c0-401f-a5d8-d1f15a1ba160",    "Success": "1",    "Error": ""}