{    "Logs": "Added object temp to s3 bucket lambda-cpp-me-south-1
    	clock precision level: 3
    	Cache line size: 64 B
    	Found an address that falls on two cache lines: 0x555555d0113c
    	Baseline sample: Size- 1500, Mean- 7283
    	[Lambda-  3] Phase, Position, Bit, Sent, Read, Lat Size, Lat Mean, Lat Std, Lat Max, Lat Min, Base Mean, Base Lat, PValue
    	[Lambda-  3]   0         7    0     0     0      1500      7094     6088    73074     5056       7283     6646 1.000811232924901
    	[Lambda-  3]   0         6    0     0     0      1500      7286     6064    52266     5030       7283     6646 1.000000205121121
    	[Lambda-  3]   0         5    0     0     0      1451     35515  1053125 40122468     5070       7283     6646 1.001770411471372
    	[Lambda-  3]   0         4    0     0     0      1480      6923     5404    42282     5054       7283     6646 1.003195374632792
    	[Lambda-  3]   0         3    0     0     0      1500      7418     6233    51292     5078       7283     6646 1.000403393085370
    	[Lambda-  3]   0         2    0     0     0      1500      8245    18297   376716     5078       7283     6646 1.007146675055913
    	[Lambda-  3]   0         1    1     1     1      1500         0        0        0        0       7283     6646 1.007146675055913
    	[Lambda-  3]   0         0    1     1     1      1500         0        0        0        0       7283     6646 1.007146675055913
    	[Lambda-3] Phase 0, Id read: 3",    "Boot ID": "e2ac42eb-ff00-4963-9ef0-506e53931ad9",    "MAC Address": "6A:40:79:DE:9F:4D",    "Phase 1": "3",    "Phases": "1",    "Start Time": "2020-08-14 00:25:55",    "End Time": "2020-08-14 00:26:25",    "Id": "3",    "Request ID": "2c0876e2-a301-4889-ad34-72e11e5593e8",    "Success": "1",    "Error": ""}