{    "Logs": "Added object temp to s3 bucket lambda-cpp-me-south-1
    	clock precision level: 3
    	Cache line size: 64 B
    	Found an address that falls on two cache lines: 0x555556a03ffc
    	Baseline sample: Size- 1500, Mean- 33853
    	[Lambda-  1] Phase, Position, Bit, Sent, Read, Lat Size, Lat Mean, Lat Std, Lat Max, Lat Min, Base Mean, Base Lat, PValue
    	[Lambda-  1]   0         7    0     0     0      1445      7221     6243    52212     4952      33853  1034509 1.002430997404709
    	[Lambda-  1]   0         6    0     0     0      1476      7003     5961    50630     4972      33853  1034509 1.002471087801832
    	[Lambda-  1]   0         5    0     0     0      1441      6968     5833    53322     4944      33853  1034509 1.002477555109678
    	[Lambda-  1]   0         4    0     0     0      1461      6874     5512    40758     4944      33853  1034509 1.002494983281149
    	[Lambda-  1]   0         3    0     0     0      1500      7102     6405    92300     4956      33853  1034509 1.002452820405474
    	[Lambda-  1]   0         2    0     0     0      1487      7559     6693    41602     4994      33853  1034509 1.002369506233629
    	[Lambda-  1]   0         1    0     0     0      1449      7464     6493    52476     4930      33853  1034509 1.002386710505427
    	[Lambda-  1]   0         0    1     1     1      1449         0        0        0        0      33853  1034509 1.002386710505427
    	[Lambda-1] Phase 0, Id read: 1",    "Boot ID": "acb0490a-9725-45d7-ad01-9bbe085d30dc",    "MAC Address": "DA:33:53:91:E6:01",    "Phase 1": "1",    "Phases": "1",    "Start Time": "2020-08-14 00:25:55",    "End Time": "2020-08-14 00:26:25",    "Id": "1",    "Request ID": "a64f5446-e23f-4f0f-bc10-fab824cca242",    "Success": "1",    "Error": ""}